### PR TITLE
Target iOS 12.5 for output

### PR DESCRIPTION
**Pull request by noahm**

### CODE REVIEW

**Comment by ranatalus** [comment]
Tested on iOS 12.5.7 on iPad Mini 2; no display. error in console is attached 
Screenshot_2023-10-09_at_1 52 42_PM

**Comment by noahm** [comment]
@ranatalus can you refresh the page and see if it changes slightly? that still looks like the error from the initial minified version, which I think is expected the first time you return to the branch to test? (the offline cache from the service worker is used initially and it serves the last version you loaded. afterwards it downloads the latest in the background and it will be used for subsequent pages visits.)

tl,dr: repeat visits to any build of the app require loading the page, waiting for a few seconds, then refreshing the page to actually see the latest changes

**Comment by ranatalus** [comment]
Revisiting the page and waiting does show me the “refresh for latest code” popup. Tapping that and refreshing has no visible change. Cleared website data and cache with no resolution in behavior. Will reconnect to Mac to get info from console tomorrow.

**Comment by ranatalus** [comment]
Connecting this morning it does attempt to load the background color change (which is progress!). Console shows these errors:
Screenshot 2023-10-10 at 9 57 13 AM


Additionally, the service worker console shows this, even though the iPad definitely has an internet connection:
Screenshot 2023-10-10 at 9 59 54 AM

**Comment by ranatalus** [comment]
Working now! There are some minor graphical glitches but nothing show stopping: 
-X icon to dismiss player choices like protect/veto does not draw correctly (tap target functions as expected)
-up/down arrow for "number of songs to draw" and level min/max does not draw correctly (button functions as expected)

BUT it's fully functional!

**Comment by ranatalus** [comment]
IMG_0005
IMG_0006

**Pull request merged**
