### PR TITLE
A20plus songs add

### PR DESCRIPTION
**Pull request by nalpan**
Adds DDR A20 Plus latest song data.
Flags of A20 Draw are tempolary disabled.

### CODE REVIEW

**Comment by nalpan** [comment]
Sorry, data format is wrong.
I'll fix wrong format.

**Comment by noahm** [comment]
Thank you for getting this started along with the other translation fix! I had just barely started working on this update last weekend but I'm happy to use this as a starting point instead. I can take care of cleaning up the data format from here if you like.

**Comment by nalpan** [comment]
@noahm Thank you for your reply!
I referred to Extream's scraper to get the data, but I find it difficult because the song title and translation will be far from the A20 data.
If you have other ideas, you can ignore this data or have this data cleaned up.

**Comment by noahm** [comment]
I just merged and deployed this! This was very helpful, and the only thing that needed to change was converting the difficulty levels from strings to numbers 7bc75fe5ec8bfb6d65e6258f683c4414ed78b4b4 so thanks a bunch for helping!

**Comment by nalpan** [comment]
@noahm 
Thank you for the wonderful work!

**Pull request closed without merging**
