### PR TITLE
add handling for "tiered" tournament packs (e.g. RIP13, Storm 2023)

### PR DESCRIPTION
**Pull request by telperion**
this PR incorporates the changes I provided VivaLaMoo for ITG @ Storm 2023 (as well as the JSON and jackets for that tourney pack).

I don't have much fluency in managed JS or TypeScript but I'm trying to learn! please bear with me haha
- ITG import script now takes an optional extra parameter to inform it whether the tournament cards are grouped into "tiers" rather than the usual level ratings
  - it assumes the tier is a square-bracketed prefix (e.g. "[T06] Multi-Thread")
- `drawGroups` and `useDrawGroups` added to props, to indicate whether the user's asking for a tier draw and which groups are available
- weighted distribution is always on if drawing from tiers (not the ideal solution, but some tiered tournament packs have nonnumeric tier names, so I didn't wanna overload the level min/max spinners for this)
- games that don't use tiers should be unaffected by these changes

### CODE REVIEW

**Comment by noahm** [comment]
This sounds neat! I'm not familiar with tiered packs, so this is all new ideas to me. I'll take a closer look later on tonight.

**Comment by noahm** [comment]
After poking at the UI in these changes, I think it introduces a lot of new complexity in both the code I would be maintaining and to the end users of the card draw (to a lesser extent). Much of that can be mitigated by being specific about the use case being supported by this new feature and resisting the urge to make it maximally flexible.

Based on the Project Storm ITG rules, it doesn't look like there's any need or desire for using weights to adjust probability on individual tiers, so while it's a convenient bit of UI to reuse, it's also the wrong one. Using weights will have unintended consequences on the probability that charts are drawn unless every tier has the same number of charts. Instead I'd be more inclined to treat tiers as difficulty types and provide a simple list of checkboxes in the same way.

However the ideal would simply replace the level spinners as you mentioned in the description. On that subject, do you have an example of a pack with non-integer tiers? Is it worth supporting those packs at the cost of making the version of card draw for Storm harder to use?

My proposal for maximizing the ease of use for this feature would be:
- make the assumption that if a pack has tiers, they will be used. do not give users an option one way or the other.
- when using a tiered pack, difficulty type options are removed (expert/challenge/etc)
- assume tiers are integers, and when using a pack with tiers, the level range selectors becomes the tier range selection
- if you feel that support for non-numeric tiers is imperative, replace the level range selectors with a checkbox list of tiers, just as the difficulty types work today
- weighted draw options can work as you have already but don't need to be forced on

**Comment by telperion** [comment]
to be honest...writing the line in the PR description about nonnumeric tiers did set the "is it actually necessary to account for nonnumeric tiers" train of thought in motion haha. previous iterations of RIP tagged songs as "Pool", "DE", or nothing (meaning they'd be used in both the pool and double elim phases), but with the advent and popularity of the waterfall format, I think we're not as likely to use that system again.

I like your proposal and agree with your rationale...let me try reimplementing for numeric tiers and I'll update the PR when I've got something ✨

**Comment by noahm** [comment]
@telperion Just pushed some changes that implements everything I suggested which allows it to really cut back on the changes to the project down to the bare minimum by piggy-backing on existing controls as much as possible. Give it a test run and let me know what you think!

**Comment by telperion** [comment]
sorry for the delay! I was finally able to try out your refactor - it's waaaaaay smoother to use.

I made a couple bugfixes, and checked them on both untiered and tiered datasets:
- eligible charts were correctly identified, but for a tiered pack, the actual chart selection went back to considering chart level with the same numeric bounds as tiers (e.g., a T08-T10 selection pooled all T08-T10 charts, but could only draw charts that were also Lv.8-10)
- weight indexing didn't seem to be taking into account that the first control would represent the lower bound of the range

**Comment by noahm** [comment]
Cool! Great catch on the first bug!

The second I think is introduced by the fact that your changes altered the configuration format such that the weights are now zero-indexed (first element is the lower bound) when before it was actually a sparse array (element at index N is the weight for charts of level N, many early elements from 0 remain undefined). I think the sparse array is an important design element, because when you have weights entered and change the bounds it keeps the weights tied to the levels they were originally given. I'm going to get these merge conflicts resolved, switch the config back to the sparse array and call it done!

**Review by noahm — APPROVED** [review]

**Pull request merged**
