### PR TITLE
Public DB schema proposal

### PR DESCRIPTION
**Pull request by noahm**
Based on [some twitter conversation that happened recently](https://twitter.com/TizaTryhards/status/1400181633005748227?s=20) the idea has come up (again) to have a publicly available database of DDR songs with metadata attached. Here's a first stab at it using the existing data I have collected for the card draw.

The approach is to assemble all of the song data into a SQLite database which is very simple to distribute and work with in just about any environment. Like the JSON format I use for the card draw, I designed the db schema here to be game agnostic. This can allow song data from other games like SDVX, Pump, etc could fit in more naturally but I'm not confident there's much value in the added flexibility that given the tradeoff in how awkward it can be to make an otherwise simple query. (more on this later)

The schema itself is visualized here: https://dbdiagram.io/d/60bbbd70b29a09603d181e80

image

In the schema, the `categories` table can categorize charts according to things like "expert" or "single" and the flags can denote things like "unlockable" or "formerly unlockable" on *both songs and individual charts*. Note that the schema allows multiple games worth of data to be contained, I'm also dubious of the value of that design decision as well. A very reasonable alternative would simply be distributing a separate database file for any given game's data.

The corresponding SQL to create the proposed schema in a SQLite database is included in this PR along with a pre-built sample DB containing my current song data for both DDR Extreme (game id 1) and DDR A20 plus (game id 2). For an example of a simple query to get single/exp/cha charts in a given difficulty range:

image

The awkwardness of all the various joins and the categories ending up in a single comma separated string column is unfortunate. With a less flexible schema designed specifically for DDR alone the style (single) and difficulty category (expert) would just be columns on the `charts` table and this would be much more straight forward.

So what does the community think? How much value is there in a more universal schema design that potentially could hold any game's song data? How useful is it to have multiple games worth of data included in a single database?

### CODE REVIEW

**Comment by vlnguyen** [comment]
My initial thoughts on a game-agnostic vs. a game-specific schema is that they should be different databases entirely.
- How much convenience is _really_ added by having a single db file versus a few others?
- How often is there a need to run cross-game queries?

Just off of those reasons alone I think they could be separate. On top of that I don't know if the schemas between games are common enough to justify it.

The only other game I play is SDVX where a large amount of the game's content is unavailable on a fresh eAmuse card, and the unlock system is convoluted. `song_flags` and `chart_flags` cover a lot of cases for tracking those, but unlock chains (you must complete this chart to unlock a different chart) is a more complex problem.

**Comment by noahm** [comment]
@vlnguyen those are good points. I don't have such fine grained metadata included for the card draw because it isn't relevant, but that sort of thing is definitely worth capturing in a more general purpose database like this.

Likewise it's convenient to have a game-agnostic format for the card draw, but that only really works because it doesn't care about lots of the miscellaneous details.

One other thing I want out of this database is to make it easy to contribute to, even for non technical folks. I'm not sure exactly how to accomplish that at the moment, but I'll keep thinking about it.

**Comment by vlnguyen** [comment]
Hm, now that I think about it, versioning on the database is going to be tricky.

**Comment by noahm** [comment]
> Hm, now that I think about it, versioning on the database is going to be tricky.

@vlnguyen I actually think this is one of the easier things to do. SQLite databases are just a single file. A single latest version can be available in a consistent location and previous versions can remain available with any sort of convention you can come up with, just like you might do with multiple copies of a excel spreadsheet.

What issues did you have in mind?

**Pull request closed without merging**
