### PR TITLE
Update drs.json

### PR DESCRIPTION
**Pull request by triadspacefight**
Update for DRS song list as of 1/4/2024 in prep for TBD4 Ver. B, as well as generally adding 300+ songs and charts that have been added to the game since 2020.

Also fixed flags to add filtering based on the following qualifiers, and added flags value to every song outside of default songlist:

            "unlock": "Stars Unlock",
            "extraExclusive": "Extra Stage/Standard Mode",
            "tempUnlock": "Event Unlock (Spark Festival, GYM, Dance Camp, KAC, etc)",
           NEW "removed": "Removed Songs (Spinnin' Records, FARM, Licenses)",
           NEW "stream": "Songs Causing Copyright Strikes (for streamers)",
           NEW "jaex": "Japanese Exclusives",
           NEW "krex": "Korea Exclusives",
           
Let me know if I can help or modify anything else. Version 3 will eventually add jackets and proper BPM info, but that's going to take some time.

### CODE REVIEW

**Comment by triadspacefight** [comment]
@noahm - apologies for the hiccup on the first request, but it seems to be fixed now with the latest file. Let me know if I need to change anything else, Vervel preview looks great to me. -Dusk

**Comment by noahm** [comment]
@triadspacefight Thanks for putting in the work to update all this! A few small things worth changing here:
- update the timestamp at `meta.lastUpdated` to mark the newly updated date for the file (should just be the output of `Date.now()` from your favorite JS engine)
- Omit any `name_translation` or `artist_translation` fields that are identical to the `name` and `artist` fields. (was already an issue in the current, outdated drs data file) This not only saves wasted bytes in filesize, but the DRS songs currently just display the title twice in the app due to the `name_translation` being present for every song. (also true of the current, outdated drs data file)
- Also omit the `flags` property when no flags apply to a song. You're currently adding an array with an empty string? (e.g. `"flags": [""]`) This might have some unintended interactions with the card draw logic.
- Finally, I added a CI-enforced formatting style with prettier just earlier tonight. You'll need to run `yarn format` in the project to rewrite this drs JSON file with the new standard style.

**Comment by triadspacefight** [comment]
> @triadspacefight Thanks for putting in the work to update all this! A few small things worth changing here:
> 
>     * update the timestamp at `meta.lastUpdated` to mark the newly updated date for the file (should just be the output of `Date.now()` from your favorite JS engine)
> 
>     * Omit any `name_translation` or `artist_translation` fields that are identical to the `name` and `artist` fields. (was already an issue in the current, outdated drs data file) This not only saves wasted bytes in filesize, but the DRS songs currently just display the title twice in the app due to the `name_translation` being present for every song. (also true of the current, outdated drs data file)
> 
>     * Also omit the `flags` property when no flags apply to a song. You're currently adding an array with an empty string? (e.g. `"flags": [""]`) This might have some unintended interactions with the card draw logic.
> 
>     * Finally, I added a CI-enforced formatting style with prettier just earlier tonight. You'll need to run `yarn format` in the project to rewrite this drs JSON file with the new standard style.

Understood! I'll make these changes and resubmit the PR later today.

**Review by triadspacefight — COMMENTED** [review]
This should be final @noahm and meet the needs outlined in your previous comment, let me know if I need to change anything else. Thanks! -Dusk

**Comment by noahm** [comment]
@triadspacefight thanks! Everything looks great now except that your most recent changes seem to have emptied out all the bpm fields for every song. I assume that wasn't intentional?

**Comment by triadspacefight** [comment]
> @triadspacefight thanks! Everything looks great now except that your most recent changes seem to have emptied out all the bpm fields for every song. I assume that wasn't intentional?

It actually was. Most of them were wrong, and BPM isn't important to gameplay as DRS speed mod is consistent across all songs. If it's an unneeded field I can just remove it altogether and resubmit.

**Comment by noahm** [comment]
Alright, sounds ok to me. I'll follow up later and make that field optional and hide the BPM text on the cards when the data is missing

**Pull request merged**
